### PR TITLE
Added FAQ section

### PR DESCRIPTION
**Pull request by mathana96**
@laurafitzgerald 
Do see if it's okay and that I haven't missed anything out.
Was a little bit unsure about the age group (12 or 13)
Thanks :)

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@mathana96 I think we have the age limit on facebook. Other than that the change looks fine

**Comment by laurafitzgerald** [comment]
@mathana96 looks like the page was added separately to this pr?

**Comment by mathana96** [comment]
@laurafitzgerald Oh yes, I will look it up. I had it pushed already and was stuck with the PR. So I made a small edit instead :see_no_evil:

**Comment by mathana96** [comment]
@laurafitzgerald Changes to age made 😄

**Pull request merged**
